Add new three stage building

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -16,6 +16,7 @@ on:
     paths-ignore:
     - README.md
     - LICENSE
+    - .dockerignore
 
 #  schedule:
 #    - cron: 0 8 * * 5
@@ -96,8 +97,8 @@ jobs:
       run: |
         echo "::set-output name=started::yes"
         . docker.sh
-        build_image multithread-compile
-        echo "::set-env name=LAST_BUILD_STAGE::multithread-compile"
+        build_image mcompile
+        echo "::set-env name=LAST_BUILD_STAGE::mcompile"
         echo "::set-output name=success::yes"
 
     # previous failure will cause current job failure
@@ -105,8 +106,8 @@ jobs:
       if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
       run: |
         . docker.sh
-        build_image singlethread-compile
-        echo "::set-env name=LAST_BUILD_STAGE::singlethread-compile"
+        build_image scompile
+        echo "::set-env name=LAST_BUILD_STAGE::scompile"
 
     - name: Push image and cache
       if: (!cancelled()) && !(failure() && github.event_name == 'repository_dispatch' && github.event.client_payload.disable_push_when_fail == true)
@@ -155,19 +156,17 @@ jobs:
     runs-on: ubuntu-18.04
     if: github.event_name == 'push' || (github.event_name == 'repository_dispatch' && github.event.action == 'docker-inc')
     env:
-      IMAGE_BASE: ${{secrets.docker_username}}/openwrt_x86_64:latest
+      IMAGE_BASE: ${{secrets.docker_username}}/openwrt_x86_64:latest-inc
       IMAGE_NAME: ${{secrets.docker_username}}/openwrt_x86_64
-      IMAGE_TAG: latest
+      IMAGE_TAG: latest-inc
       CONTEXT: .
       BUILDX_DRIVER: docker
       DOCKERFILE: Dockerfile-inc
       REPO_URL: https://github.com/coolsnowwolf/lede
       REPO_BRANCH: master
       CONFIG_FILE: 'config.diff'
-      BUILD_WHOLE: ${{ github.event.client_payload.build_whole || false }}
       NO_REMOTE_CACHE: 1
-      NO_PUSH: 1
-      BUILD_ARGS: 'CONFIG_FILE IMAGE_BASE BUILD_WHOLE'
+      BUILD_ARGS: 'CONFIG_FILE IMAGE_BASE UPDATE_REPO UPDATE_FEEDS'
 
     steps:
     - name: Checkout
@@ -179,12 +178,23 @@ jobs:
       with:
         version: latest
 
-    - name: Configure docker
+    - name: Init and configure docker
+      env:
+        UPDATE_FEEDS: ${{ github.event.client_payload.update_feeds }}
+        UPDATE_REPO: ${{ github.event.client_payload.update_repo }}
       run: |
+        echo "::set-env name=UPDATE_FEEDS::${UPDATE_FEEDS}"
+        echo "::set-env name=UPDATE_REPO::${UPDATE_REPO}"
         scripts/cleanup.sh
         . docker.sh
         configure_docker
         login_to_registry
+
+    - name: Use latest base image
+      if: github.event_name == 'repository_dispatch' && github.event.client_payload.use_latest == true
+      run: |
+        . docker.sh
+        create_tag_alias ${IMAGE_NAME}:latest ${IMAGE_BASE}
 
     - name: Pull base image
       run: |
@@ -198,11 +208,23 @@ jobs:
         TIMEOUT_MIN: 5
       uses: tete1030/debugger-action@my
 
+    - name: Update repo and packages
+      run: |
+        . docker.sh
+        build_image updateclone
+        echo "::set-env name=LAST_BUILD_STAGE::updateclone"
+
     - name: Apply customizations
       run: |
         . docker.sh
-        build_image applycustom
-        echo "::set-env name=LAST_BUILD_STAGE::applycustom"
+        build_image custom
+        echo "::set-env name=LAST_BUILD_STAGE::custom"
+
+    - name: Download package
+      run: |
+        . docker.sh
+        build_image download
+        echo "::set-env name=LAST_BUILD_STAGE::download"
 
     - name: Multi-thread compile
       id: mtcompile
@@ -210,8 +232,8 @@ jobs:
       run: |
         echo "::set-output name=started::yes"
         . docker.sh
-        build_image multithread-compile
-        echo "::set-env name=LAST_BUILD_STAGE::multithread-compile"
+        build_image mcompile
+        echo "::set-env name=LAST_BUILD_STAGE::mcompile"
         echo "::set-output name=success::yes"
 
     # previous failure will cause current job failure
@@ -219,8 +241,14 @@ jobs:
       if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
       run: |
         . docker.sh
-        build_image singlethread-compile
-        echo "::set-env name=LAST_BUILD_STAGE::singlethread-compile"
+        build_image scompile
+        echo "::set-env name=LAST_BUILD_STAGE::scompile"
+
+    - name: Push image
+      if: (!cancelled()) && !(failure() && github.event_name == 'repository_dispatch' && github.event.client_payload.disable_push_when_fail == true)
+      run: |
+        . docker.sh
+        push_image
 
     - name: Copy out bin directory
       id: copydir
@@ -241,7 +269,7 @@ jobs:
         path: openwrt/bin
 
     - name: Organize files
-      if: steps.copydir.outputs.status == 'success' && !cancelled() && github.event_name == 'repository_dispatch' && github.event.client_payload.build_whole == true
+      if: steps.copydir.outputs.status == 'success' && !cancelled()
       run: |
         cd openwrt/bin/targets/*/*
         rm -rf packages
@@ -249,10 +277,153 @@ jobs:
   
     - name: Upload firmware
       uses: actions/upload-artifact@master
-      if: steps.copydir.outputs.status == 'success' && success() && !cancelled() && github.event_name == 'repository_dispatch' && github.event.client_payload.build_whole == true
+      if: steps.copydir.outputs.status == 'success' && success() && !cancelled()
       with:
         name: OpenWrt_firmware
         path: ${{ env.FIRMWARE }}
+
+    # failure checking
+    - name: SSH connection to Actions
+      if: failure() || (github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true)
+      uses: tete1030/debugger-action@my
+
+  docker-build-package:
+    runs-on: ubuntu-18.04
+    if: github.event_name == 'push' || (github.event_name == 'repository_dispatch' && github.event.action == 'docker-package')
+    env:
+      IMAGE_BASE: ${{secrets.docker_username}}/openwrt_x86_64:latest-package
+      IMAGE_NAME: ${{secrets.docker_username}}/openwrt_x86_64
+      IMAGE_TAG: latest-package
+      CONTEXT: .
+      BUILDX_DRIVER: docker
+      DOCKERFILE: Dockerfile-package
+      REPO_URL: https://github.com/coolsnowwolf/lede
+      REPO_BRANCH: master
+      CONFIG_FILE: 'config.diff'
+      NO_REMOTE_CACHE: 1
+      BUILD_ARGS: 'CONFIG_FILE IMAGE_BASE UPDATE_FEEDS'
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@master
+
+    - name: Set up Docker Buildx
+      id: buildx
+      uses: crazy-max/ghaction-docker-buildx@v1
+      with:
+        version: latest
+
+    - name: Init and configure docker
+      env:
+        UPDATE_FEEDS: ${{ github.event.client_payload.update_feeds }}
+      run: |
+        echo "::set-env name=UPDATE_FEEDS::${UPDATE_FEEDS}"
+        scripts/cleanup.sh
+        . docker.sh
+        configure_docker
+        login_to_registry
+        touch .start_timestamp
+
+    - name: Use latest base image
+      if: github.event_name == 'repository_dispatch' && ( github.event.client_payload.use_latest == true || github.event.client_payload.use_latest_inc == true )
+      env:
+        USE_LATEST: ${{ github.event.client_payload.use_latest }}
+        USE_LATEST_INC: ${{ github.event.client_payload.use_latest_inc }}
+      run: |
+        . docker.sh
+        if [ "x${USE_LATEST}" = "x1" ]; then
+          test "x${USE_LATEST}" != "x1"
+          create_tag_alias ${IMAGE_NAME}:latest ${IMAGE_BASE}
+        else
+          create_tag_alias ${IMAGE_NAME}:latest-inc ${IMAGE_BASE}
+        fi
+
+    - name: Pull base image
+      run: |
+        . docker.sh
+        pull_image
+
+    # Allow intermediate customization
+    - name: SSH connection to Actions
+      if: github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true
+      env:
+        TIMEOUT_MIN: 5
+      uses: tete1030/debugger-action@my
+
+    - name: Apply customizations
+      run: |
+        . docker.sh
+        build_image custom
+        echo "::set-env name=LAST_BUILD_STAGE::custom"
+
+    - name: Download package
+      run: |
+        . docker.sh
+        build_image download
+        echo "::set-env name=LAST_BUILD_STAGE::download"
+
+    - name: Multi-thread compile
+      id: mtcompile
+      continue-on-error: true
+      run: |
+        echo "::set-output name=started::yes"
+        . docker.sh
+        build_image mcompile
+        echo "::set-env name=LAST_BUILD_STAGE::mcompile"
+        echo "::set-output name=success::yes"
+
+    # previous failure will cause current job failure
+    - name: Single-thread compile
+      if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
+      run: |
+        . docker.sh
+        build_image scompile
+        echo "::set-env name=LAST_BUILD_STAGE::scompile"
+
+    - name: Push image
+      if: (!cancelled()) && !(failure() && github.event_name == 'repository_dispatch' && github.event.client_payload.disable_push_when_fail == true)
+      run: |
+        . docker.sh
+        push_image
+
+    - name: Copy out bin directory
+      id: copydir
+      if: (!cancelled())
+      run: |
+        . docker.sh
+        if [ ! -d "$(pwd)/openwrt" ]; then
+          mkdir "$(pwd)/openwrt"
+        fi
+        copy_files /home/builder/openwrt/bin "$(pwd)/openwrt/bin"
+        echo "::set-output name=status::success"
+
+    - name: Remove firmware
+      if: steps.copydir.outputs.status == 'success' && !cancelled()
+      run: |
+        shopt -s extglob
+        cd openwrt/bin/targets/*/*
+        all_extra_files=( !(packages) )
+        rm -rf "${all_extra_files[@]}"
+
+    - name: Upload packages
+      uses: actions/upload-artifact@master
+      if: steps.copydir.outputs.status == 'success' && !cancelled()
+      with:
+        name: OpenWrt_packages
+        path: openwrt/bin
+
+    - name: Remove old packages
+      if: steps.copydir.outputs.status == 'success' && !cancelled()
+      run: |
+        cd openwrt/bin/targets/*/*
+        find . -type f -not -newer ../../../../../.start_timestamp -exec rm -f {} \;
+
+    - name: Upload new packages
+      uses: actions/upload-artifact@master
+      if: steps.copydir.outputs.status == 'success' && !cancelled()
+      with:
+        name: OpenWrt_new_packages
+        path: openwrt/bin
 
     # failure checking
     - name: SSH connection to Actions
@@ -275,7 +446,9 @@ jobs:
       env: 
         REPO_URL: https://github.com/coolsnowwolf/lede
         REPO_BRANCH: master
-      run: scripts/clone.sh
+      run:
+        scripts/update_repo.sh
+        UPDATE_FEEDS=1 scripts/update_feeds.sh
 
     - name: Load custom configuration
       env:
