Rename all jobs

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -2,7 +2,7 @@
 # https://github.com/P3TERX/Actions-OpenWrt
 # Description: Build OpenWrt using GitHub Actions
 # Lisence: MIT
-# Author: P3TERX (for direct-build job)
+# Author: P3TERX (for build-direct job)
 # Blog: https://p3terx.com
 #=================================================
 
@@ -69,18 +69,18 @@ jobs:
         ${{toJSON(github)}}
         EOF
 
-  docker-build:
+  build-base:
     runs-on: ubuntu-18.04
     if: |
       (
         github.event_name == 'push' &&
-        contains(github.event.head_commit.message, '#build#')
+        contains(github.event.head_commit.message, '#build-base#')
       ) || (
         github.event_name == 'repository_dispatch' && 
-        github.event.action == 'docker-build'
+        github.event.action == 'build-base'
       ) || (
         github.event_name == 'deployment' && 
-        github.event.deployment.task == 'docker-build'
+        github.event.deployment.task == 'build-base'
       )
     name: ${{matrix.title}}
     strategy:
@@ -89,9 +89,9 @@ jobs:
         mode: [normal, test]
         include:
         - mode: normal
-          title: docker-build
+          title: build-base
         - mode: test
-          title: Fast checking docker-build
+          title: Fast checking build-base
     env:
       # Not recommended to change as they are already in optimal condition
       # 不推荐修改，已处在最优状态
@@ -231,7 +231,7 @@ jobs:
         github.event.deployment.payload.debug == true
       uses: tete1030/debugger-action@my
 
-  docker-build-inc:
+  build-inc:
     runs-on: ubuntu-18.04
     if: | 
       (
@@ -239,10 +239,10 @@ jobs:
         contains(github.event.head_commit.message, '#build-inc#')
       ) || (
         github.event_name == 'repository_dispatch' && 
-        github.event.action == 'docker-build-inc'
+        github.event.action == 'build-inc'
       ) || (
         github.event_name == 'deployment' && 
-        github.event.deployment.task == 'docker-build-inc'
+        github.event.deployment.task == 'build-inc'
       )
     name: ${{matrix.title}}
     strategy:
@@ -251,14 +251,12 @@ jobs:
         mode: [normal, test]
         include:
         - mode: normal
-          title: docker-build-inc
+          title: build-inc
         - mode: test
-          title: Fast checking docker-build-inc
+          title: Fast checking build-inc
     env:
       # Not recommended to change as they are already in optimal condition
       # 不推荐修改，已处在最优状态
-      # Using docker driver instead of docker-container because we don't need cache
-      # 由于不需要缓存，这里使用docker而非docker-container
       DK_BUILD_ARGS: 'REPO_URL REPO_BRANCH CONFIG_FILE DK_IMAGE_BASE OPT_UPDATE_REPO OPT_UPDATE_FEEDS'
 
     steps:
@@ -448,7 +446,7 @@ jobs:
         github.event.deployment.payload.debug == true
       uses: tete1030/debugger-action@my
 
-  docker-build-package:
+  build-package:
     runs-on: ubuntu-18.04
     if: |
       (
@@ -456,10 +454,10 @@ jobs:
         contains(github.event.head_commit.message, '#build-package#')
       ) || (
         github.event_name == 'repository_dispatch' && 
-        github.event.action == 'docker-build-package'
+        github.event.action == 'build-package'
       ) || (
         github.event_name == 'deployment' && 
-        github.event.deployment.task == 'docker-build-package'
+        github.event.deployment.task == 'build-package'
       )
     name: ${{matrix.title}}
     strategy:
@@ -468,14 +466,12 @@ jobs:
         mode: [normal, test]
         include:
         - mode: normal
-          title: docker-build-package
+          title: build-package
         - mode: test
-          title: Fast checking docker-build-package
+          title: Fast checking build-package
     env:
       # Not recommended to change as they are already in optimal condition
       # 不推荐修改，已处在最优状态
-      # Using docker driver instead of docker-container because we don't need cache
-      # 由于不需要缓存，这里使用docker而非docker-container
       DK_BUILD_ARGS: 'CONFIG_FILE DK_IMAGE_BASE OPT_UPDATE_FEEDS'
 
     steps:
@@ -557,7 +553,7 @@ jobs:
             ret_val=$?
           set -eo pipefail
           if [ "x${ret_val}" != "x0" ]; then
-            echo "::error::Base/incremental builder '${BUILDER_ID_SELECTED}' does not exist, please run 'docker-build'/'docker-build-inc' job" >&2
+            echo "::error::Base/incremental builder '${BUILDER_ID_SELECTED}' does not exist, please run 'build-base'/'build-inc' job" >&2
             exit 1
           fi
 
@@ -656,14 +652,18 @@ jobs:
       if: failure() || github.event.client_payload.debug == true || github.event.deployment.payload.debug == true
       uses: tete1030/debugger-action@my
 
-  direct-build:
+  build-direct:
     runs-on: ubuntu-18.04
-    if: (
+    if: |
+      (
+        github.event_name == 'push' &&
+        contains(github.event.head_commit.message, '#build-direct#')
+      ) || (
         github.event_name == 'repository_dispatch' &&
-        github.event.action == 'direct-build'
+        github.event.action == 'build-direct'
       ) || (
         github.event_name == 'deployment' &&
-        github.event.deployment.task == 'direct-build'
+        github.event.deployment.task == 'build-direct'
       )
     steps:
     - name: Checkout
