Fixed checking of push

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -61,7 +61,9 @@ jobs:
 
     steps:
     - name: Checkout
-      uses: actions/checkout@master
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
 
     - name: Init build env
       env:
@@ -73,21 +75,55 @@ jobs:
 
     - name: Check if skip this job
       run: |
-        set +eo pipefail
-        BUILD_TARGET_ESC="$(echo "${BUILD_TARGET}" | sed 's/[^[:alnum:]_-]/\\&/g')"
-        git show --pretty="" --name-only | grep -q '^user/'"${BUILD_TARGET_SEC}"'/'
-        ret_val=$?
         SKIP_TARGET=1
-        if [ ! -z "${REPO_DISPATCH_ACTION}" -o ! -z "${DEPLOYMENTS_TASK}" ]; then
+        if [ "x${GITHUB_EVENT_NAME}" = "xpush" ]; then
+          push_before="${{github.event.before}}"
+          push_after="${{github.event.after}}"
+
+          if [ -z "${push_before}" -o -z "${push_after}" ]; then
+            echo "::error::Oops! Something went wrong! Github push event does not exist!" >&2
+            exit 1
+          fi
+
+          # when forcing push, we cannot compare
+          if git cat-file -e ${push_before}^{commit} ; then
+            true
+          else
+            echo "::error::Force push not supported, skipping job" >&2
+            echo "::set-env name=SKIP_TARGET::1"
+            exit 0
+          fi
+
+          echo "Changes in this push:"
+          git --no-pager diff --name-status ${push_before} ${push_after}
+          changed_files="$(git --no-pager diff --name-only ${push_before} ${push_after})"
+
+          BUILD_TARGET_ESC="$(echo "${BUILD_TARGET}" | sed 's/[^[:alnum:]_-]/\\&/g')"
+          set +e
+            echo "${changed_files}" | grep -q '^user/'"${BUILD_TARGET_ESC}"'/'
+            ret_val=$?
+          set -e
+
+          if [ ${ret_val} -eq 0 ]; then
+            SKIP_TARGET=0
+          else
+            SKIP_TARGET=1
+          fi
+        elif [ ! -z "${REPO_DISPATCH_ACTION}" -o ! -z "${DEPLOYMENTS_TASK}" ]; then
           if [ "x${REPO_DISPATCH_ACTION}" = "x${BUILD_TARGET}" -o "x${DEPLOYMENTS_TASK}" = "x${BUILD_TARGET}" ]; then
             SKIP_TARGET=0
           else
             SKIP_TARGET=1
           fi
-        elif [ ${ret_val} -eq 0 ]; then
-          SKIP_TARGET=0
         else
-          SKIP_TARGET=1
+          echo "::warning::Unknown triggering event, no skipping" >&2
+          SKIP_TARGET=0
+        fi
+
+        if [ "x${SKIP_TARGET}" = "x1" ]; then
+          echo "Skipping current job"
+        else
+          echo "Not skipping current job"
         fi
         echo "::set-env name=SKIP_TARGET::${SKIP_TARGET}"
 
