Add checking of base builder #build-inc#

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -18,8 +18,8 @@
 env:
   # Specify here the name and tag you want to use for the builders
   # 在这里自定义你想使用的Builder名和默认Tag
-  BUILDER_NAME: openwrt
-  BUILDER_TAG: dev
+  BUILDER_NAME: openwrt_dev
+  BUILDER_TAG: latest
   # Specify here the OpenWrt Repo URL and Branch
   # 在这里指定你的OpenWrt的Repo URL和Branch
   REPO_URL: https://github.com/coolsnowwolf/lede
@@ -294,17 +294,28 @@ jobs:
         configure_docker
         login_to_registry
 
-    - name: Check if use latest base image
+    - name: Check if using latest base builder
       env:
         BOOL_USE_LATEST: ${{ github.event.client_payload.use_latest || github.event.deployment.payload.use_latest }}
       run: |
         . docker.sh
+        # temporarily disable failure guarder
         set +eo pipefail
         docker buildx imagetools inspect "${IMAGE_BASE}"
         ret_val=$?
         set -eo pipefail
         if [ "x${BOOL_USE_LATEST}" = "xtrue" -o "x${ret_val}" != "x0" ]; then
-          echo "Creating '${IMAGE_BASE}' from '${IMAGE_LATEST}'"
+          echo "Creating incremental builder '${IMAGE_BASE}' from base builder '${IMAGE_LATEST}'"
+
+          set +eo pipefail
+          docker buildx imagetools inspect "${IMAGE_LATEST}"
+          ret_val=$?
+          set -eo pipefail
+          if [ "x${ret_val}" != "x0" ]; then
+            echo "::error::Base builder '${IMAGE_LATEST}' does not exist, please run 'docker-build' job" >&2
+            exit 1
+          fi
+
           create_remote_tag_alias "${IMAGE_LATEST}" "${IMAGE_BASE}"
         fi
 
@@ -476,12 +487,13 @@ jobs:
         login_to_registry
         touch .start_timestamp
 
-    - name: Check if use latest base image
+    - name: Check if using latest base builder
       env:
         BOOL_USE_LATEST: ${{ github.event.client_payload.use_latest || github.event.deployment.payload.use_latest }}
         BOOL_USE_LATEST_INC: ${{ github.event.client_payload.use_latest_inc || github.event.deployment.payload.use_latest_inc }}
       run: |
         . docker.sh
+        # temporarily disable failure guarder
         set +eo pipefail
         docker buildx imagetools inspect "${IMAGE_BASE}"
         ret_val=$?
@@ -490,12 +502,22 @@ jobs:
           IMAGE_SELECTED="${IMAGE_LATEST}"
           if [ "x${BOOL_USE_LATEST_INC}" = "xtrue" ]; then
             if [ "x${BOOL_USE_LATEST}" = "xtrue" ]; then
-              echo "You cannot use both 'use_latest' and 'use_latest_inc'" >&2
+              echo "::error::You cannot use both 'use_latest' and 'use_latest_inc'" >&2
               exit 1
             fi
             IMAGE_SELECTED="${IMAGE_LATEST_INC}"
           fi
-          echo "Creating '${IMAGE_BASE}' from '${IMAGE_SELECTED}'"
+          echo "Creating incremental builder '${IMAGE_BASE}' from '${IMAGE_SELECTED}'"
+
+          set +eo pipefail
+          docker buildx imagetools inspect "${IMAGE_SELECTED}"
+          ret_val=$?
+          set -eo pipefail
+          if [ "x${ret_val}" != "x0" ]; then
+            echo "::error::Base/incremental builder '${IMAGE_SELECTED}' does not exist, please run 'docker-build' job" >&2
+            exit 1
+          fi
+
           create_remote_tag_alias "${IMAGE_SELECTED}" "${IMAGE_BASE}"
         fi
 
