Use absolute paths, use tmpfs for source rebuild

diff --git a/.github/workflows/squash.yml b/.github/workflows/squash.yml
--- a/.github/workflows/squash.yml
+++ b/.github/workflows/squash.yml
@@ -82,7 +82,7 @@ jobs:
         . scripts/host/docker.sh
         # temporarily disable failure guarder
         set +eo pipefail
-          IMAGE_DIGEST="$(docker buildx imagetools inspect --raw "${BUILDER_ID_INC}" | perl -pe 'chomp if eof' | openssl dgst -sha256 2>/dev/null ;  exit ${PIPESTATUS[0]})"
+          IMAGE_DIGEST="$(docker buildx imagetools inspect --raw "${BUILDER_IMAGE_ID_INC}" | perl -pe 'chomp if eof' | openssl dgst -sha256 2>/dev/null ;  exit ${PIPESTATUS[0]})"
           image_check_ret_val=$?
         set -eo pipefail
 
@@ -98,24 +98,24 @@ jobs:
       if: env.SKIP_TARGET == '0'
       run: |
         . scripts/host/docker.sh
-        STRICT_PULL=1 pull_image "${BUILDER_ID_INC}"
+        STRICT_PULL=1 pull_image "${BUILDER_IMAGE_ID_INC}"
 
     - name: Squash builder when necessary
       if: env.SKIP_TARGET == '0'
       run: |
         . scripts/host/docker.sh
-        DK_LAYER_NUMBER_LIMIT=10 squash_image_when_necessary "${BUILDER_ID_INC}"
+        DK_LAYER_NUMBER_LIMIT=10 squash_image_when_necessary "${BUILDER_IMAGE_ID_INC}"
 
     - name: Upload squashed builder
       if: env.SKIP_TARGET == '0'
       run: |
         . scripts/host/docker.sh
-        TMP_BUILDER_ID="${BUILDER_ID_INC}-squashtmp"
-        docker tag "${BUILDER_ID_INC}" "${TMP_BUILDER_ID}"
-        docker push "${TMP_BUILDER_ID}"
+        TMP_BUILDER_IMAGE_ID="${BUILDER_IMAGE_ID_INC}-squashtmp"
+        docker tag "${BUILDER_IMAGE_ID_INC}" "${TMP_BUILDER_IMAGE_ID}"
+        docker push "${TMP_BUILDER_IMAGE_ID}"
 
         set +eo pipefail
-          CUR_IMAGE_DIGEST="$(docker buildx imagetools inspect --raw "${BUILDER_ID_INC}" | perl -pe 'chomp if eof' | openssl dgst -sha256 2>/dev/null ;  exit ${PIPESTATUS[0]})"
+          CUR_IMAGE_DIGEST="$(docker buildx imagetools inspect --raw "${BUILDER_IMAGE_ID_INC}" | perl -pe 'chomp if eof' | openssl dgst -sha256 2>/dev/null ;  exit ${PIPESTATUS[0]})"
           image_check_ret_val=$?
         set -eo pipefail
 
@@ -125,7 +125,7 @@ jobs:
         fi
 
         if [ "x${CUR_IMAGE_DIGEST}" != "x${IMAGE_DIGEST}" ]; then
-          echo "::error::Image '${BUILDER_ID_INC}' has changed during squashing, aborting" >&2
+          echo "::error::Image '${BUILDER_IMAGE_ID_INC}' has changed during squashing, aborting" >&2
         else
-          create_remote_tag_alias "${TMP_BUILDER_ID}" "${BUILDER_ID_INC}"
+          create_remote_tag_alias "${TMP_BUILDER_IMAGE_ID}" "${BUILDER_IMAGE_ID_INC}"
         fi
